set(_CATKIN_CURRENT_PACKAGE "generate_bag")
set(generate_bag_VERSION "1.0.0")
set(generate_bag_MAINTAINER "Jack Shade, Team 22 <jnshade@ncsu.edu>")
set(generate_bag_PACKAGE_FORMAT "2")
set(generate_bag_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(generate_bag_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(generate_bag_BUILDTOOL_DEPENDS "catkin")
set(generate_bag_BUILDTOOL_EXPORT_DEPENDS )
set(generate_bag_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(generate_bag_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(generate_bag_TEST_DEPENDS )
set(generate_bag_DOC_DEPENDS )
set(generate_bag_URL_WEBSITE "")
set(generate_bag_URL_BUGTRACKER "")
set(generate_bag_URL_REPOSITORY "")
set(generate_bag_DEPRECATED "")